In [13]:
import numpy as np
import random

In [14]:
np.random.randint(0,9,size=(3,2))

array([[6, 7],
       [5, 2],
       [3, 3]])

In [15]:
np.ones((5,6),dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
a = [1,2,3,4,5,6]
b = [[9,8,7,6],[4,5,2]]
print(a)
print(type(a))
print(b)
print(type(b))

[1, 2, 3, 4, 5, 6]
<class 'list'>
[[9, 8, 7, 6], [4, 5, 2]]
<class 'list'>


In [17]:
print(b[0][2])

7


In [18]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
type(a)
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [19]:
print(a[1][5])
print(a[1,5])

13
13


In [20]:
# get a specific row
print(a[0])
print(a[0,:])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [21]:
#get a specific column
a[:,2]

array([ 3, 10])

#  This one is important :

In [22]:
# all are separated by colon(:)
# 1st parameter implies takeallrows which is-   :,
# 2nd parameter implies startindex which is 1
# 3rd parameter implies endindex which is 6
# 4th parameter implies stepsize which is 2


a[:,1:6:2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

In [23]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [24]:
a[1,5]=31
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 31, 14]])

In [25]:
a[:, 2] = [500,1000]
a

array([[   1,    2,  500,    4,    5,    6,    7],
       [   8,    9, 1000,   11,   12,   31,   14]])

In [59]:
# this one replaces all the elements from both the rows
a[:,] = 899
a

array([[899, 899, 899, 899, 899, 899, 899],
       [899, 899, 899, 899, 899, 899, 899]])